CREATE TABLE IF NOT EXISTS hr_user (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(45) NOT NULL,
  last_name VARCHAR(45) NOT NULL,
  email VARCHAR(45) NOT NULL,
  username VARCHAR(45) UNIQUE NULL,
  password VARCHAR(255) NULL,
  enabled TINYINT NOT NULL DEFAULT 1
  );

CREATE TABLE IF NOT EXISTS user_role (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  username varchar(45) NOT NULL,
  role VARCHAR(45) NOT NULL,
  FOREIGN KEY (username) REFERENCES hr_user (username)
);

CREATE TABLE IF NOT EXISTS todo (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  description VARCHAR(255) NOT NULL,
  creation_date TIMESTAMP NOT NULL,
  completed TINYINT NOT NULL DEFAULT 0,
  FOREIGN KEY (user_id) REFERENCES hr_user (id)
);


